version: "3"
services: 
  back:
    image: eliseoeric/quotes-back:1
    volumes:
      - ./back/:/app
    ports:
      - "3000:3000"
    networks:
      - kubeapp
  data:
    container_name: data
    image: eliseoeric/quotes-data:1
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks: 
      - kubeapp

networks:
  kubeapp: