version: '3.3'

services:
  app:
    image: openjdk:8-jre-alpine
    volumes:
      - .:/app
    entrypoint:
      - /usr/bin/java
      - -jar
      - -Dspring.profiles.active=dev
      - /spring-boot.jar
    ports:
      - ${APP_PORT:-8080}:8080

  maven:
    build:
      context: .
      dockerfile: Dockerfile.maven
    working_dir: /app
    volumes:
      - .:/app